### PR TITLE
WIP: run-time configuration

### PR DESCRIPTION
**Pull request by vortigont**
This is still work-in-progress, but I thought that @mrfaptastic you might wanna look into this and test/add some feedback for other panel types that I do not have.
What is done:
 - dynamic class configuration on initialization, no need to change defines in .h files
 - some internal structures replaced with dynamically allocated/managed objects
 - obsolete fast/slow mode, now it is always "fast", brightness control takes care of control bits on-change
 - flicker-less brightness control in 'fast' mode

known issues:
 - artefacts every 128 column (FIXED)
 - some times fine gradients looks harsh/some times not, might be brightness related issue (FIXED)

P.S. It breaks the API a little bit ) (FIXED)

### CODE REVIEW

**Comment by vortigont** [comment]
something is working :)
HUB75_ctrl

**Comment by mrfaptastic** [comment]
Thanks for this. I have created a new branch and made a pull request from your repository. There's a lot of change to merge into the master. My main concern is keeping backwards compatability.

**Comment by vortigont** [comment]
Got it, thanks. Actually only begin([pins]) is incompatible with custom pin mapping. I could overload it with wrapper to cfg struct to keep an old option compatible.
As for the other methods I only removed fastmode() switcher that I've introduced not so long ago.
Pls, feel free to review and post your comments, it is still work in progress anyway :)

**Comment by mrfaptastic** [comment]
By the way, this is really good stuff so thank you again for your contribution. If you could create an overload warpper to the cfg struct for begin() that would be excellent.

Any ideas what might cause the artefact at column 128? I'll take a look and see if i see anything on my non-FM panels.

**Comment by vortigont** [comment]
You are welcome ) Have some other ideas in mind also
Yes, I've already fixed that artefacts, will push update later today along with overloaded begin(). But need more tests with colours/brightness.
And just to make it clear - only the existing option for pin definition's could be reassigned via begin(). Most of the other stuff like modules size's etc could be defined on class instance creation only to prevent out-of-bounds issues.
Might think about full reinitialization options in future though :)

**Comment by vortigont** [comment]
Pushed a commit with compatibility overloads and a fix for column artefacts.

**Comment by vortigont** [comment]
So, it looks pretty good for me now, no visible artefacts left. Need more testers with other matrixes to confirm/report issues :)
Also might need to change existing examples one way or another.

**Comment by mrfaptastic** [comment]
Farkin fantastic work as always! Good stuff! Going to test it tonight. I like how you've c++ ified the framebuffer structs more instead of being a mix of old c code.

**Comment by vortigont** [comment]
thanks! yup, took me a while to dig through those nested arrays :)
But I like the whole idea of this library - looks pretty ) Pls, feel free to revise my comments and code for syntax/grammar/spelling. English is not my native, so as cpp, he he :)

**Comment by mrfaptastic** [comment]
Hi vortigont, I'm giving you access to the repo directly, please feel free to make changes to the dev branch directly. If you want to propose changes to the main branch can you please raise/propose pull requests from your repo. Thank you.

**Comment by vortigont** [comment]
Oh, that's very kind of you, Thanks!
Will update some more examples to the new format than to prepare it for the upcoming merge.
Won't touch master branch.
Cheers!

**Pull request closed without merging**
