### PR TITLE
Virtual panel 16x32 panels

### PR DESCRIPTION
**Pull request by mrRobot62**
Includes now a virtual 16x32 panel with drawing lines, text and scrolling text.

### CODE REVIEW

**Comment by mrfaptastic** [comment]
Excellent contribution. Merging this into the dev branch instead. Thank you

**Comment by mrRobot62** [comment]
No prob - The scrolling text implementation - may be a good extension for the existing library. What do you think? If so, I can try to work on it once I get my 32x65 display

**Comment by mrfaptastic** [comment]
Hi mrRobot62,

The scope of this library is a hardware interface for raw pixel output to RGB matrix's using DMA, not a higher-order graphics library.

i.e. AdaFruit GFX Library -> Pixel Colour & Co-ords -> This Library -> DMA based signal output to HUB75

The best place for this scrolling text implementation would be it's own example. Similar to how we have GraphicsLayer, BitmapIcons, AnimatedGif examples etc.

If people want to have a 32x16 scrolling display, then they mash together the code from both examples.

**Comment by mrfaptastic** [comment]
Thanks again for your fantastic contribution @mrRobot62. I've updated your example in the dev branch FYI.

**Comment by mrRobot62** [comment]
Hi, ok thanks from my side.

Yeah, I’m not a native english speaker - sorry for wrong words and/or grammar :-)

Cheers
Bernd




Viele Grüße
Bernd

www.myyl.com/balance

**Pull request merged**
