### PR TITLE
Clock phase toggling option

### PR DESCRIPTION
**Pull request by vortigont**
This change would allow to use MBI5124 matrixes out of the box (Issue #75 ).
@DerMaulwurf, pls test [this](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/tree/clkphase) branch since you are the only one having this matrix for now.

Should work if being set like this

```
HUB75_I2S_CFG mxconfig(
				PANEL_RES_X,   // module width
				PANEL_RES_Y,   // module height
				PANEL_CHAIN    // Chain length
	);
mxconfig.driver = HUB75_I2S_CFG::MBI5124;

```

### CODE REVIEW

**Comment by DerMaulwurf** [comment]
I'm happy to test the version. Because I'm on the road this weekend, I won't get to it until Sunday.

**Comment by DerMaulwurf** [comment]
The new code works fine. The MBI5124 works as the second in a chain of four panels. There is no visable difference between the various chipsets.

**Comment by mrfaptastic** [comment]
Inverting the clock makes no different on my standard dumb-shift register only panel (ICS chipset).

@vortigont - Should we not just have the clock inverted by default then instead?

**Comment by vortigont** [comment]
Well, that's a good question... one way or another some chips could be affected. 6126 also seems to be fine with inverted clock, so we could change  default phase to '1' (inverted) until some else reports it as an issue :)
Also as I can see from the 6126 datasheet, register counts it's control data on rising edges and it is implemented this way in "init procedure". For now it is not relevant since it' being done via manual bitbanging, but I'm still thinking about implementing it via DMA run one day... Than I'm gonna need to "invert" 6126 from default's setting :)
IMO let's keep it this way like in this PR. It would be easy either to select chip-driver or simply set `mxconfig.clkphase = true;` for any new/strange chipset that could possible pop out of nowhere anytime :)

**Comment by mrfaptastic** [comment]
Ok. I agree, lets leave the default as it curently is then... As the old saying goes "If it ain't broke, don't try and fix it" :-)

**Comment by vortigont** [comment]
Thanks, @mrfaptastic, I will add some readme/doc info for this option later.

**Pull request merged**
