### PR TITLE
CI job to test examples builds

### PR DESCRIPTION
**Pull request by vortigont**
Hi @mrfaptastic,
I've made a small CI job to test lib code on new commits/PRs. Currenly only one example tested with PIO configuration. If you like the idea than some other examples could also be converted to PIO format and involved into CI tests. Pls, check this, once merged it should enable "Actions" item in repo's features with a reports being sent to email if any issues found.

Cheers!

### CODE REVIEW

**Comment by vortigont** [comment]
Hi @mrfaptastic, tnx for merging this! Could you pls check if you have 'actions' menu under repo's settings? It has to be turned on to run GitHub's runners and have the CI logs available. Tnx!

**Comment by mrfaptastic** [comment]
I've enabled the actions menu. I have no idea how to get the workflow to trigger though.

**Comment by vortigont** [comment]
Nice! It should auto trigger on each push/PR to master, currently it will build "examples/PIO_TestPatterns" only, and if it hits any build error you should receive an e-mail notification. Also build logs should be available on [actions](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA/actions) page. If we put some other examples also to this job it could be a great help to catch some regression errors. I'll make a new dev branch for testing this.

**Comment by mrfaptastic** [comment]
Ahhh man. Does this mean my days of randomly breaking stuff are over? :-D

**Comment by mrfaptastic** [comment]
Looks like it might need some tweaking. Pushed a change to the git and it triggered the workflow, but I got some email about it saying the workflow failed to start.

**Comment by vortigont** [comment]
> Ahhh man. Does this mean my days of randomly breaking stuff are over? :-D

yeah... that's the idea :) gonna miss good old days?



> Looks like it might need some tweaking

Pls, allow it to be `Allow all actions ` under `Actions permissions` section
It's kind of misleading but `actions/checkout@v2, actions/cache@v2, and actions/setup-python@v2` are foreign to your repo, but it's just some GitHub's internals that allows to use git and python withing the build container, no risks there.

**Comment by mrfaptastic** [comment]
Merry Christmas. Looks to be running well.
I had a question for you, if we wanted to implement the setmuxpattern functionality of the pxmatrix library into this library, where should this be done?

I appreciate we've highly optimised this library for 'BINARY' muxpattern type.

https://github.com/2dom/PxMatrix/blob/master/PxMatrix.h

**Comment by vortigont** [comment]
Merrry X-Mas! :) I'm not familiar with setmuxpattern of pxmatrix lib, let me check into this more close and I'll may come with some ideas )

**Pull request merged**
